/*
 *  Created: 
 * Modified:  
 */

package ae.threadpooltest.random;

import java.util.concurrent.Callable;


/**
 * @author Albin Engström
 */
public class RandMaker implements Callable<Double>{
	
	/**
	 * Calculates the mean of the values generated by random
	 * 
	 * @return the mean of the values
	 */
	public Double call(){
		
		//Create a new Random object
		Random random = new Random();
		
		//Gets required constants
		int nrValues = ae.threadpooltest.constants.Constants.VALUES_PER_THREAD;
		
		//Variable to hold the sum
		double sum = 0.0;
		
		//Calculates the sum of nrValues number of values
		for(int i = 0; i < nrValues; i++){
			sum += random.next();
		} 
		
		//Returns the mean
	    return sum/nrValues;
	}
}
