/*
 *  Created: 
 * Modified:  
 */

package ae.threadpooltest.random;


/**
 * @author Albin Engström
 */
public class RandMaker{
	
	/**
	 * A Random object
	 */
	private static Random random = new Random();
	
	/**
	 * Calculates the mean of the values generated by random
	 * 
	 * @param nrValues number of values to count with
	 * @return the mean of the values
	 */
	public static double run(int nrValues){
		
		//Variable to hold the sum
		double sum = 0.0;
		
		//Calculates the sum of nrValues number of values
		for(int i = 0; i < nrValues; ++i){
			sum += random.next();
		} 
		
		//Returns the mean
	    return sum/nrValues;
	}
}
